apiVersion: app/v1
kind: Service
metadata:
  name: helloworld-nodejs
spec:
  template:
    spec:
      replicas: 2
      containers:
        - image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
          env:
            - name: TARGET
              value: "Node.js sample v1"