apiVersion: apps/v1
kind: Deployment
metadata:
  name: ahmed
  labels:
    app: ahmed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx0
  template:
    metadata:
      labels:
        app: nginx0
    spec:
      containers:
      - name: nginx
        image: $DOCKER_IMAGE_NAME:latest
        ports:
        - containerPort: 80
            
    