apiVersion: v1
kind: Service
metadata:
    app: Hello
  name: Hello
spec:
  type: NodePort
  ports:
  - port:80
  selector:
    app: Hello
 ---
 apiVersion: apps/v1
kind: Deployment
metadata:
  name: Hello
spec:
  replicas: 2
  selector:
    spec:
       containsers:
       -  name: Hello
          image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
          ports:
          - port: 80         
    