apiVersion: v1
kind: Service
metadata:
  app: hello
  name: hello
spec:
  type: NodePort
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 3
    spec:
       containsers:
       - name: hello
         image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
         ports:
         - port: 80         
    